spring:
  application:
    name: BookmarkYourManga
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  jpa:
    # Par défaut "postgresql" renseigné pour être explicite
    database: postgresql
  datasource:
    # Par défaut "org.postgresql.Driver" renseigné pour être explicite
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082
logging:
  pattern:
    console: "%clr(%d){cyan} [%clr(%p)] %clr(%c){magenta} - %m%n"
  level:
    root: info
    com.wd.bym: info
bym:
  batch:
    launcher:
      mode: command-line
mal:
  api-version: "v2"
  client-header: "X-MAL-CLIENT-ID"
  url: "https://api.myanimelist.net"