spring:
  application:
    name: BookmarkYourManga
  profiles:
    active: local
  output:
    ansi:
      enabled: always
  jpa:
    # Par défaut "postgresql" renseigné pour être explicite
    database: postgresql
  datasource:
    # Par défaut "org.postgresql.Driver" renseigné pour être explicite
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  servlet:
    context-path: /bym
logging:
  pattern:
    console: "%clr(%d){cyan} [%clr(%p)] %clr(%c){magenta} - %m%n"
  level:
    root: info
    com.wd.bym: info
bym:
  batch:
    launcher:
      mode: service