spring:
  application:
    name: BookmarkYourManga
  profiles:
    active: core,local
  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  servlet:
    context-path: /bym
logging:
  pattern:
    console: "%clr(%d){cyan} [%clr(%p)] %clr(%c){magenta} - %m%n"
  level:
    root: info
    com.wd.bym: info
bym:
  batch:
    launcher:
      mode: service